name: .NET

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/WorkerServiceSolution.sln

    - name: Build
      run: dotnet build ./src/WorkerService/WorkerService.csproj --configuration Release

    - name: Test
      run: dotnet test ./src/WorkerService.Tests/WorkerService.Tests.csproj --configuration Release --collect:"XPlat Code Coverage" --logger:"trx;LogFileName=../TestResults.trx"

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Generate Coverage Report
      run: reportgenerator -reports:./**/coverage.cobertura.xml -targetdir:./CoverageReport -reporttypes:Html

    - name: Extract Coverage Percentage
      id: coverage
      run: |
        # Install xmllint if not already installed
        sudo apt-get update
        sudo apt-get install -y libxml2-utils bc

        # Find the coverage file
        coverage_file=$(find . -name "coverage.cobertura.xml" -type f -print -quit)
        if [ -z "$coverage_file" ]; then
          echo "Coverage file not found!"
          exit 1
        fi
        echo "Coverage file found: $coverage_file"

        # Extract the 'line-rate' attribute from the root <coverage> element
        coverage_percentage=$(xmllint --xpath "string(/coverage/@line-rate)" "$coverage_file")
        if [ -z "$coverage_percentage" ]; then
          echo "Failed to extract coverage percentage!"
          exit 1
        fi
        echo "Raw Coverage Percentage: $coverage_percentage"

        # Convert the decimal coverage to percentage
        coverage_percentage=$(echo "$coverage_percentage * 100" | bc -l)

        # Round to two decimal places
        coverage_percentage=$(printf "%.2f" "$coverage_percentage")

        echo "Coverage Percentage: $coverage_percentage%"

        # Set the output variable
        echo "coverage_percentage=$coverage_percentage" >> $GITHUB_OUTPUT

    - name: Print Coverage Percentage
      run: |
        echo "Coverage Percentage: ${{ steps.coverage.outputs.coverage_percentage }}%"
